services:
    mariadb:
      container_name: mariadb
      image: mariadb:1.0
      env_file:
        .env
      build:
        context: ./requirements/mariadb
        dockerfile: Dockerfile
      restart: always
      volumes:
        - mariadbDB:/var/lib/mysql
      networks:
        - intra

    nginx:
      container_name: nginx
      image: nginx:1.0
      build:
        context: ./requirements/nginx
        dockerfile: Dockerfile
      env_file:
        .env
      restart: always
      ports:
        - "443:443"
      volumes:
        - wordpressDB:/var/www/html
      depends_on:
        - wordpress
      networks:
        - intra

    wordpress:
      container_name: wordpress
      image: wordpress:1.0
      depends_on:
        - mariadb
      env_file:
        .env
      build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
      restart: always
      volumes:
        - wordpressDB:/var/www/html
      networks:
        - intra

networks:
    intra:
      driver: bridge

volumes:
    wordpressDB:
    mariadbDB: