version: '3'
services:
 nginx:
  build: . #[도커 파일 경로] 이렇게 하면 알아서 도커파일을 참조한다.
  ports:
   - "8080:80" #호스트의 8080포트를 컨테이너의 80번 포트에 연결한다.
  networks:
   - costom-network

networks:
 costom-network:
  driver: bridge # 도커에서 기본으로 사용하는 네트워크 드라이버로, 브리지 네트워크는 여러 컨테이너가 하나의 네트워크에 연결되어 서로 통신할 수 있게 한다.